---
title: "Introduction to densr"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```



Welcome to the `densr` package, a powerful tool designed to enhance your data analysis by providing methods to overlay histograms with various density estimation techniques. This vignette will guide you through the installation process and demonstrate the usage of the `create_hist_dens` function, a central component of the package.

## Installation

To get started, you need to install the `densr` package. If you haven't installed the `devtools` package yet, uncomment the first line in the code below:

```
# install.packages("devtools")  # Uncomment if devtools is not installed
devtools::install_github("rachel-mc/densr")
library(densr)
#Now that you have the densr package installed, let's explore its functionalities.
```

#### Creating Density Histograms
Create_hist_dens is the main function used to make density histograms. It creates an object of class "hist_dens" which contains the histogram information, density numbers, and the particular method used for estimating density.

```
# Load the package and example dataset
library(densr)
data(mtcars)

# Create a density histogram using the default settings
hist_dens_obj <- create_hist_dens(mtcars$mpg)
```

#### Density Estimation Types
The create_hist_dens function allows you to specify different types of density estimation. The available options are:
"gaussian": Gaussian density estimation.
"kde": Kernel density estimation.
"fp": Frequency polygon density estimation.
```
# Create a kernel density estimate
hist_dens_kde <- create_hist_dens(mtcars$mpg, type = "kde", bw = 2)

# Create a frequency polygon estimate
hist_dens_fp <- create_hist_dens(iris$Sepal.Length, type = "fp")
```

#### Plotting Density Histograms
To visualize the created objects of class "hist_dens," you can use the dedicated plotting function plot.hist_dens.

```
# Plot the kernel density estimate
plot(hist_dens_kde)
```
#### Package Information
The `densr` package provides additional functions to complement your density estimation workflow:

frequency_polygon: Create a frequency polygon type density estimation.
plot.hist_dens: A plotting method for objects of class "hist_dens."
```
# Example of using frequency_polygon
freq_poly <- frequency_polygon(mtcars$mpg)
```
### Conclusion
The `densr` package is a useful tool. It combines different methods for estimating density into your histograms smoothly. By trying out various kinds and settings, you can get deep understanding of your data collections.

If you encounter any issues or have suggestions, please report them on https://github.com/rachel-mc/densr









