
#' Plot create_hist_dens output
#'
#' Plotting method for objects inheriting from class \code{"hist_dens"}.
#' Overlays a density estimate based on the type specified i.e. gaussian, kde,
#' or fp, to a histogram of the same data supplied to
#' \code{\link{create_hist_dens}}.
#'
#' @param x An object of class \code{"hist_dens"} generated by
#' \code{\link{create_hist_dens}}.
#' @param ... Catches unused arguments to \code{plot}, \code{curve}
#' or \code{lines}.
#'
#' @return Nothing in the Console. A histogram of numeric data with an
#' explicitly stated density option superimposed on it is produced in the Plots
#' window.
#'
#' @family densr
#'
#' @export
#' @author Rachel McInerney - <\email{rachel.mcinerney.2021@@mumail.ie}>,
#'         Conor Thompson - <\email{conor.thompsongargan.2020@@mumail.ie}>,
#'         Osi Ukachukwu - <\email{osi.ukachukwu.2018@@mumail.ie}>
#'
#' @seealso \code{\link{create_hist_dens}} for how to create objects of class
#' \code{"hist_dens"}
#'
#' @examples
#' dat1 <- create_hist_dens(ChickWeight$weight, type = "kde", kernel = "epanechnikov")
#' plot(dat1, lwd = 2)
#' dat2 <- create_hist_dens(USArrests$Assault, type = "fp")
#' plot(dat2, lty = 4)
plot <- function(x, ...) {
  UseMethod("plot")
}

#' @export
plot.hist_dens <- function(x, ...) {

  if(!inherits(x, "hist_dens")) stop("x must be of class \"hist_dens\"")
  # returns an error if x is not of class "hist_dens"

  h <- x$h # Pull out histogram, density, type and data from hist_dens object
  d <- x$d
  type <- x$type
  x <- x$x

  mu <- mean(x)
  sigma <- stats::sd(x)

  h |>
    base::plot(freq = FALSE, ...) # for density histogram
  # object of class histogram is plotted by plot.histogram

  switch(type,
         gaussian = graphics::curve(dnorm(x, mu, sigma), add = TRUE, ...),
         kde = graphics::lines(d, ...),
         fp = graphics::lines(d$vx, d$vy, ...))
}

# Respects the genericFunction.class() naming convention
# A method must implement the arguments in the generic at a minimum, but may contain further named arguments if desired
# Our plot.method() matches the arguments of the generic 'plot' which already exists (see formals(plot) : x, ...)
# We use curve() to overlay normal densities from dnorm() and lines to overlay the other density options
